# Generated by Django 3.0.4 on 2020-03-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('attrition', models.CharField(blank=True, max_length=200, null=True)),
                ('businesstravel', models.CharField(blank=True, max_length=200, null=True)),
                ('dailyrate', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('distancefromhome', models.IntegerField(blank=True, null=True)),
                ('education', models.IntegerField(blank=True, null=True)),
                ('educationfield', models.CharField(blank=True, max_length=200, null=True)),
                ('employeecount', models.IntegerField(blank=True, null=True)),
                ('employeenumber', models.IntegerField(blank=True, null=True)),
                ('environmentsatisfaction', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('hourlyrate', models.IntegerField(blank=True, null=True)),
                ('jobinvolvement', models.IntegerField(blank=True, null=True)),
                ('joblevel', models.IntegerField(blank=True, null=True)),
                ('jobrole', models.CharField(blank=True, max_length=200, null=True)),
                ('jobsatisfaction', models.IntegerField(blank=True, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=200, null=True)),
                ('monthlyincome', models.IntegerField(blank=True, null=True)),
                ('monthlyrate', models.IntegerField(blank=True, null=True)),
                ('numcompaniesworked', models.IntegerField(blank=True, null=True)),
                ('over18', models.CharField(blank=True, max_length=200, null=True)),
                ('overtime', models.CharField(blank=True, max_length=200, null=True)),
                ('percentsalaryhike', models.IntegerField(blank=True, null=True)),
                ('performancerating', models.IntegerField(blank=True, null=True)),
                ('relationshipsatisfaction', models.IntegerField(blank=True, null=True)),
                ('standardhours', models.IntegerField(blank=True, null=True)),
                ('stockoptionlevel', models.IntegerField(blank=True, null=True)),
                ('totalworkingyears', models.IntegerField(blank=True, null=True)),
                ('trainingtimeslastyear', models.IntegerField(blank=True, null=True)),
                ('worklifebalance', models.IntegerField(blank=True, null=True)),
                ('yearsatcompany', models.IntegerField(blank=True, null=True)),
                ('yearsincurrentrole', models.IntegerField(blank=True, null=True)),
                ('yearssincelastpromotion', models.IntegerField(blank=True, null=True)),
                ('yearswithcurrmanager', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mytable',
                'managed': False,
            },
        ),
    ]
